# Base configs
baseurl: #"https://brick-dev.github.io/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: #""

# UI configs
title: "Brick builds by brick_dev"
subtitle: ""
author: "brick_dev"
header:
 title: "brick_dev"
 subtitle: "Building with bricks"
footer:
 name: ""
 bio: "This is my website showing brick builds!."
 github: "More text here!"
web_design: ""
social_urls:
  facebook: #"https://www.facebook.com/ramswaroop"
  twitter: https://twitter.com/brick_dev
  instagram: #"https://www.instagram.com/ram_patra"
  dribbble: #"https://dribbble.com/rampatra"
  linkedin: #"https://in.linkedin.com/in/ram-patra"
  github: https://github.com/brick-dev
